---
title: "LinearReg"
output: pdf_document
date: "2024-05-28"
---

```{r}
library(car)
install.packages("readxl")
library(readxl)
install.packages("dplyr")
library(dplyr)
install.packages("lubridate")
library(lubridate)
library(forecast)
library(ggplot2)
```

```{r}

```



```{r}
number_of_employees <- read_excel("~/Desktop/Unipd/GitHub/Business-Project/Business Project/number-of-employees.xlsx")
quarterly_net_income <- read_excel("~/Desktop/Unipd/GitHub/Business-Project/Business Project/quarterly-net-income.xlsx")
rd_spending <- read_excel("~/Desktop/Unipd/GitHub/Business-Project/Business Project/research-development-spending.xlsx")
revenue_by_quarter <- read_excel("~/Desktop/Unipd/GitHub/Business-Project/Business Project/revenue-by-quarter.xlsx")
revenue_by_segment <- read_excel("~/Desktop/Unipd/GitHub/Business-Project/Business Project/revenue-by-segment.xlsx")
```

```{r}
number_of_employees <- read_excel("~/Uni/Business/Business Project/Untitled/Business-Project/Business Project/number-of-employees.xlsx")
revenue_by_quarter_2 <- read_excel("~/Uni/Business/Business Project/Untitled/Business-Project/Business Project/New_Data_2.xlsx")
rd_spending <- read_excel("~/Uni/Business/Business Project/Untitled/Business-Project/Business Project/research-development-spending.xlsx")
quarterly_net_income <- read.csv("~/Uni/Business/Business Project/Untitled/Business-Project/Business Project/net_income_csv.csv")
revenue_by_quarter <- read_excel("~/Uni/Business/Business Project/Untitled/Business-Project/Business Project/revenue-by-quarter.xlsx")
revenue_by_segment <- read_excel("~/Uni/Business/Business Project/Untitled/Business-Project/Business Project/revenue-by-segment.xlsx")
nvda_stock <- read.csv("~/Uni/Business/Business Project/Untitled/Business-Project/Business Project/NVDA.csv")
number_of_employees_2 <- read_excel("~/Uni/Business/Business Project/Untitled/Business-Project/Business Project/NVIDIA_Employees_Data.xlsx")

```

```{r}
#plot with ggplot2 quarterly_net_income x from 1 to len df
#reverse Quarter Value Year
quarterly_net_income <- data.frame(quarter = rev(quarterly_net_income$Quarter), Value = rev(quarterly_net_income$Value), Year = rev(quarterly_net_income$Year))

#delete last 2 rowns of the dataframe

quarterly_net_income <- quarterly_net_income[-c((nrow(quarterly_net_income)-1):nrow(quarterly_net_income)),]

ggplot(quarterly_net_income, aes(x = 1:nrow(quarterly_net_income), y = Value, group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "Quarterly Net Income", x = "Index", y = "Net Income (Billion)") +
  theme_minimal()
```


```{r}

nvda_stock <- nvda_stock %>% mutate(Price = (Open + Adj.Close) / 2)

nvda_stock <- nvda_stock %>% select(Date, Price)

nvda_stock$Date <- as.Date(nvda_stock$Date, format="%Y-%m-%d")

nvda_stock <- nvda_stock %>%
  mutate(Year = year(Date),
         Quarter = quarter(Date))

quarterly_data <- nvda_stock %>%
  group_by(Year, Quarter) %>%
  summarise(Average_Price = mean(Price, na.rm = TRUE)) %>%
  ungroup()



head(nvda_stock)


head(quarterly_data)

#assigning the quarterly data to nvda_stock
nvda_stock <- quarterly_data
nvda_stock <- nvda_stock %>% mutate(quarter = rep(c("Q1", "Q2", "Q3", "Q4"), length.out = nrow(nvda_stock)))


ggplot(quarterly_data, aes(x = paste(Year, Quarter, sep = "-Q"), y = Average_Price, group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "Average Price per Quarter", x = "Year-Quarter", y = "Average Price") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(quarterly_data, aes(x = paste(Year, Quarter, sep = "-Q"), y = log(Average_Price), group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "Average Price per Quarter", x = "Year-Quarter", y = "Average Price") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```
```{r}
nvda_stock <- nvda_stock %>% select(Year, 'Average_Price', quarter) %>% rename(Price = 'Average_Price')
```



```{r}
#print all colnames and types of the columns
print(colnames(number_of_employees))
print(sapply(number_of_employees, class))
print(nrow(number_of_employees))

print(colnames(number_of_employees_2))
print(sapply(number_of_employees_2, class))
print(nrow(number_of_employees_2))

print(colnames(revenue_by_quarter))
print(sapply(revenue_by_quarter, class))
print(nrow(revenue_by_quarter))

print(colnames(revenue_by_quarter_2))
print(sapply(revenue_by_quarter_2, class))
print(nrow(revenue_by_quarter_2))

print(colnames(rd_spending))
print(sapply(rd_spending, class))
print(nrow(rd_spending))

print(colnames(quarterly_net_income))
print(sapply(quarterly_net_income, class))
print(nrow(quarterly_net_income))

print(colnames(nvda_stock))
print(sapply(nvda_stock, class))
print(nrow(nvda_stock))
```


```{r}
# Normalizzare i dati
normalize <- function(x) {
  return((x - mean(x)) / sd(x))
}

# Ripetere i valori annuali per ciascuno dei quattro trimestri
repeat_annual_data <- function(annual_data) {
  return(rep(annual_data, each = 4))
}
```

```{r}
plot_model_forecast <- function(model, data, forecast_horizon) {
  forecasted_values <- forecast(model, h = forecast_horizon)
  plot(forecasted_values, ylab = "Billion", xlab = "Time")
  lines(fitted(model), col = 2)
}
```


```{r}
```



```{r}
#print every firsst value of the dataframes (columns 'Date')
print(head(number_of_employees_2$Date, 1))
print(head(rd_spending$year, 1))
print(head(quarterly_net_income$Year, 1))
print(head(revenue_by_quarter$quarter, 1))
print(head(revenue_by_quarter_2$Date, 1))
print(head(nvda_stock$Year, 1))
```


```{r}
#fix revenue_by_quarter_2
#delete last 4 rows of the dataframe revenue_by_quarter_2
revenue_by_quarter_2 <- revenue_by_quarter_2[-c((nrow(revenue_by_quarter_2)-3):nrow(revenue_by_quarter_2)),]

#reverse all revenue_by_quarter_2 columns values (Revenue and Date)
revenue_by_quarter_2 <- data.frame(Revenue = rev(revenue_by_quarter_2$Revenue), Date = rev(revenue_by_quarter_2$Date))

#add Q1 Q2 Q3 Q4 to a new column Quarter
revenue_by_quarter_2 <- revenue_by_quarter_2 %>%
  mutate(Quarter = rep(c("Q1", "Q2", "Q3", "Q4"), length.out = nrow(revenue_by_quarter_2)))

#add column Year with reapeted values from 1999 to 2024 (every year 4 times)
revenue_by_quarter_2 <- revenue_by_quarter_2 %>%
  mutate(Year = rep(1999:2024, each = 4, length.out = nrow(revenue_by_quarter_2)))

#delete column "Date" from the dataframe
revenue_by_quarter_2 <- revenue_by_quarter_2 %>% select(-Date)

```

```{r}
#fix rd_spending
# Carica i pacchetti necessari
install.packages("splines")
library(splines)

# Dati annuali
anni <- rd_spending$year

valori_annuali <- rd_spending$billion / 1000

# Definizione dei punti trimestrali
punti_trimestrali <- seq(2005, 2023, by = 0.25)

# Interpolazione cubica
spline_fit <- spline(anni, valori_annuali, xout = punti_trimestrali, method = "natural")

# Creazione di un data frame per visualizzare i risultati
df_trimestrale <- data.frame(Anno_Trimestre = spline_fit$x, Valore = spline_fit$y)

rd_spending <- df_trimestrale

#add a column year from 2005 to 2023 repeated 4 times for each year

rd_spending <- rd_spending %>%
  mutate(year = rep(2005:2023, each = 4, length.out = nrow(rd_spending)))

#add a column quarter with values Q1 Q2 Q3 Q4 each repeated 4 times for each year
rd_spending <- rd_spending %>%
  mutate(quarter = rep(c("Q1", "Q2", "Q3", "Q4"), length.out = nrow(rd_spending)))


#delete column Annno_Trimestre
rd_spending <- rd_spending %>% select(-Anno_Trimestre)


# Mostra i risultati
print(rd_spending)
```

```{r}
#plot with ggplot2 rd_spending x from 1 to len df

ggplot(rd_spending, aes(x = 1:nrow(rd_spending), y = Valore, group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "Research & Development Spending", x = "Index", y = "Spending (Billion)") +
  theme_minimal()

ggplot(rd_spending, aes(x = year, y = Valore, group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "Research & Development Spending", x = "Index", y = "Spending (Billion)") +
  theme_minimal()


```
```{r}
#fix number_of_employees_2
#delete last 2 rows of the dataframe number_of_employees_2
number_of_employees_2 <- number_of_employees_2[-c((nrow(number_of_employees_2)-1):nrow(number_of_employees_2)),]

#delete Change and Growth columns
number_of_employees_2 <- number_of_employees_2 %>% select(-Change, -'Growth (%)')

#reverse all number_of_employees_2 columns values (Numbers of Emplyees and Date)
number_of_employees_2 <- data.frame(Values = rev(number_of_employees_2$'Number of Employees'), Date = rev(number_of_employees_2$Date))

#add a clumn year from 1999 to 2024 not repeated call it Year
number_of_employees_2 <- number_of_employees_2 %>%
  mutate(year = rep(1999:2024, length.out = nrow(number_of_employees_2)))

# Dati annuali
anni <- number_of_employees_2$year

valori_annuali <- number_of_employees_2$Values

# Definizione dei punti trimestrali
punti_trimestrali <- seq(1999, 2024, by = 0.25)

# Interpolazione cubica
spline_fit <- spline(anni, valori_annuali, xout = punti_trimestrali, method = "natural")

# Creazione di un data frame per visualizzare i risultati
df_trimestrale <- data.frame(Anno_Trimestre = spline_fit$x, Valore = spline_fit$y)

number_of_employees_2 <- df_trimestrale

#add a column year from 1999 to 2024 repeated 4 times for each year

number_of_employees_2 <- number_of_employees_2 %>%
  mutate(year = rep(1999:2024, each = 4, length.out = nrow(number_of_employees_2)))

#add a column quarter with values Q1 Q2 Q3 Q4 each repeated 4 times for each year
number_of_employees_2 <- number_of_employees_2 %>%
  mutate(quarter = rep(c("Q1", "Q2", "Q3", "Q4"), length.out = nrow(number_of_employees_2)))

#drop column Anno_Trimestre
number_of_employees_2 <- number_of_employees_2 %>% select(-Anno_Trimestre)

#plot with ggplot2 number_of_employees_2 x from 1 to len df

ggplot(number_of_employees_2, aes(x = 1:nrow(number_of_employees_2), y = Valore, group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "Number of Employees", x = "Index", y = "Number of Employees") +
  theme_minimal()

#plot with ggplot2 number_of_employees_2 per year

ggplot(number_of_employees_2, aes(x = year, y = Valore, group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "Number of Employees", x = "Year", y = "Number of Employees") +
  theme_minimal()


```


```{r}
# Carica i pacchetti necessari
if(!require(tidyverse)) install.packages("tidyverse")
if(!require(splines)) install.packages("splines")

# Supponiamo che rd_spending sia già definito nel tuo ambiente di lavoro

# Crea df per poly
df <- rd_spending %>% select(Valore)
# Reverti l'ordine del df
df <- rev(df$Valore)

# Trasforma il df in un dataframe con colonne chiamate Valore e time
df <- data.frame(Valore = df)
df$time <- 1:nrow(df)

# Crea un modello di regressione spline
model <- lm(Valore ~ ns(time, df = 1), data = df) # ns = natural splines, df = gradi di libertà

# Numero di punti da predire (ad esempio, 24 punti all'indietro)
n_pred <- 24

# Creazione di un dataframe per la predizione
new_data <- data.frame(time = nrow(df) + 1:n_pred)

# Predizione dei valori
predicted_values <- predict(model, newdata = new_data)

# Assicurati che i valori predetti non siano minori di zero
predicted_values <- pmax(predicted_values, 0)

# Aggiungi i valori predetti al dataframe
new_data$Valore <- predicted_values

# Mostra i valori predetti
print(new_data)
```


```{r}
#aggiunge colonne year da 1999 al 2004 a new_data repeated 4 times for each year and a column quarter with values Q1 Q2 Q3 Q4 repeated 4 times for each year
new_data <- new_data %>%
  mutate(year = rep(1999:2004, each = 4, length.out = nrow(new_data)))

new_data <- new_data %>% mutate(quarter = rep(c("Q1", "Q2", "Q3", "Q4"), length.out = nrow(new_data)))

#drop column 'time'
new_data <- new_data %>% select(-time)

#reverse all new_data columns values (Valore, year, quarter)
new_data <- data.frame(Valore = rev(new_data$Valore), year = new_data$year, quarter = new_data$quarter)

rd_spending <- rbind(new_data, rd_spending)
```

```{r}
#plot with ggplot2 rd_spending x from 1 to len df

ggplot(rd_spending, aes(x = 1:nrow(rd_spending), y = Valore, group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "Research & Development Spending", x = "Index", y = "Spending (Billion)") +
  theme_minimal()
```
```{r}
#print every firsst value of the dataframes (columns 'Date')
print(head(number_of_employees_2$year, 1))
print(head(rd_spending$year, 1))
print(head(quarterly_net_income$Year, 1))
print(head(revenue_by_quarter_2$Year, 1))
print(head(nvda_stock$Year, 1))

print(head(number_of_employees_2$quarter, 1))
print(head(rd_spending$quarter, 1))
print(head(quarterly_net_income$quarter, 1))
print(head(revenue_by_quarter_2$Quarter, 1))
print(head(nvda_stock$quarter, 1))
```
```{r}
#print every firsst value of the dataframes (columns 'Date')
print(tail(number_of_employees_2$year, 1))
print(tail(rd_spending$year, 1))
print(tail(quarterly_net_income$Year, 1))
print(tail(revenue_by_quarter_2$Year, 1))
print(tail(nvda_stock$Year, 1))

print(tail(number_of_employees_2$quarter, 1))
print(tail(rd_spending$quarter, 1))
print(tail(quarterly_net_income$quarter, 1))
print(tail(revenue_by_quarter_2$Quarter, 1))
print(tail(nvda_stock$quarter, 1))
```
```{r}
# delete the first 4 rows and the last 5 rows of the dataframe number_of_employees_2
number_of_employees_2 <- number_of_employees_2[-c(1:4, (nrow(number_of_employees_2)-4):nrow(number_of_employees_2)),]

# delete the first 4 rows and the last 1 rows of the dataframe rd_spending
rd_spending <- rd_spending[-c(1:4, (nrow(rd_spending)):nrow(rd_spending)),]

# delete the first 2 rows and the last 4 rows of the dataframe quarterly_net_income
quarterly_net_income <- quarterly_net_income[-c(1:2, (nrow(quarterly_net_income)-3):nrow(quarterly_net_income)),]

# delete the first 4 rows and the last 5 rows of the dataframe revenue_by_quarter_2
revenue_by_quarter_2 <- revenue_by_quarter_2[-c(1:4, (nrow(revenue_by_quarter_2)-4):nrow(revenue_by_quarter_2)),]

# delete the first 4 rows and the last 6 rows of the dataframe nvda_stock
nvda_stock <- nvda_stock[-c(1:4, (nrow(nvda_stock)-5):nrow(nvda_stock)),]

```

```{r}
# round with no decimal the values of the column Valore of number_of_employees_2
number_of_employees_2 <- number_of_employees_2 %>% mutate(Valore = round(Valore, 0))
```


```{r}
ts_employees <- ts(number_of_employees_2$Valore, frequency = 4)
ts_net_income <- ts(quarterly_net_income$Value, frequency = 4)
ts_spending <- ts(rd_spending$Valore, frequency = 4)
ts_revenue <- ts(revenue_by_quarter_2$Revenue, frequency = 4)
ts_stock <- ts(nvda_stock$Price, frequency = 4)

```

```{r}
#aggretgate all timesereis in a dataframe

data_combined <- data.frame(
  revenue = ts_revenue,
  net_income = ts_net_income,
  employees = ts_employees,
  rnd_spending = ts_spending,
  stock = ts_stock
)

print(head(data_combined))

```
```{r}
#plot data_combined
ggplot(data_combined, aes(x = 1:nrow(data_combined), y = net_income, group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "Revenue", x = "Index", y = "Revenue (Billion)") +
  theme_minimal()
```
```{r}
#split the data into training and test set

train_size <- 0.87
train_index <- round(nrow(data_combined) * train_size)

train_data <- data_combined[1:train_index, ]
test_data <- data_combined[(train_index + 1):nrow(data_combined), ]

print(nrow(train_data))
print(nrow(test_data))

#esctract terget y from train and test that is ts_revenue

train_y <- ts_revenue[1:train_index]
test_y <- ts_revenue[(train_index + 1):nrow(data_combined)]

print(length(train_y))
print(length(test_y))

#divide target from features
train_x <- train_data %>% select(-revenue)
test_x <- test_data %>% select(-revenue)

print(nrow(train_x))
print(nrow(test_x))

```
```{r}
#plot features and target

ggplot(train_data, aes(x = 1:nrow(train_data), y = revenue, group = 1)) +
  geom_line() +
  geom_point() +
  labs(title = "Revenue", x = "Index", y = "Revenue (Billion)") +
  theme_minimal()

ggplot(train_data, aes(x = 1:nrow(train_data), y = net_income, group = 1)) + 
  geom_line() +
  geom_point() +
  labs(title = "Net Income", x = "Index", y = "Net Income (Billion)") +
  theme_minimal()

ggplot(train_data, aes(x = 1:nrow(train_data), y = employees, group = 1)) + 
  geom_line() +
  geom_point() +
  labs(title = "Number of Employees", x = "Index", y = "Number of Employees") +
  theme_minimal()

ggplot(train_data, aes(x = 1:nrow(train_data), y = rnd_spending, group = 1)) + 
  geom_line() +
  geom_point() +
  labs(title = "Research & Development Spending", x = "Index", y = "Spending (Billion)") +
  theme_minimal()

ggplot(train_data, aes(x = 1:nrow(train_data), y = stock, group = 1)) + 
  geom_line() +
  geom_point() +
  labs(title = "Stock Price", x = "Index", y = "Price") +
  theme_minimal()

#plot test data
ggplot(test_data, aes(x = 1:nrow(test_data), y = revenue, group = 1)) + 
  geom_line() +
  geom_point() +
  labs(title = "Revenue", x = "Index", y = "Net Income (Billion)") +
  theme_minimal()


```


```{r}
#transform train_y and train_x in time series

train_y <- ts(train_y, frequency = 4)
train_x <- ts(train_x, frequency = 4)
```

```{r}
train_x_df <- data.frame(train_x)
```

```{r}

tslm_rev <- tslm(train_y ~ trend + season + train_x, data = train_x)
summary(tslm_rev) # ts_employees non è significativa

checkresiduals(tslm_rev)
vif(tslm_rev)
```


```{r}
fit <- fitted(tslm_rev)
fore <- forecast(tslm_rev, newdata = test_x)

# PLOT THE FORECAST AND THE ACTUAL VALUES TOGETHER FOR COMPARISON 
plot(fore, main = "Forecast vs Actual Revenue", xlab = "Time", ylab = "Revenue (Billion)", ylim = c(0, 10))
lines(ts_revenue, col = "black")
lines(fit, col = "red")
legend("topleft", legend = c("Forecast", "Actual"), col = c("blue", "red"), lty = 1)

```



```{r}

# Calcolo della matrice di correlazione
correlation_matrix <- cor(train_x, use = "complete.obs")

# Visualizzazione della matrice di correlazione
print(correlation_matrix)

# Se desideri una visualizzazione grafica
library(corrplot)
corrplot(correlation_matrix, method = "circle")

# Creazione del dataframe con le serie differenziate
train_x_diff <- diff(train_x)

# Calcolo della matrice di correlazione
correlation_matrix_diff <- cor(train_x_diff, use = "complete.obs")

# Visualizzazione della matrice di correlazione
print(correlation_matrix_diff)

# Visualizzazione grafica della matrice di correlazione
corrplot(correlation_matrix_diff, method = "circle")

```


```{r}

tslm_rev <- tslm(diff(train_y) ~ trend + season + train_x_diff, data = train_x_diff)
summary(tslm_rev) # ts_employees non è significativa

checkresiduals(tslm_rev)
vif(tslm_rev)
```

```{r}
fit <- fitted(tslm_rev)
fore <- forecast(tslm_rev, newdata = test_x)

# PLOT THE FORECAST AND THE ACTUAL VALUES TOGETHER FOR COMPARISON 
plot(fore, main = "Forecast vs Actual Revenue", xlab = "Time", ylab = "Revenue (Billion)", ylim = c(-5, 10))
lines(ts_revenue, col = "black")
lines(fit, col = "red")
legend("topleft", legend = c("Forecast", "Actual"), col = c("blue", "red"), lty = 1)

```


```{r}
# Funzione per calcolare gli errori
calculate_errors <- function(actual, forecast) {
  ME <- mean(actual - forecast) # Mean Error
  RMSE <- sqrt(mean((actual - forecast)^2)) # Root Mean Squared Error
  MAE <- mean(abs(actual - forecast)) # Mean Absolute Error
  MPE <- mean((actual - forecast) / actual) * 100 # Mean Percentage Error
  MAPE <- mean(abs((actual - forecast) / actual)) * 100 # Mean Absolute Percentage Error
  return(list(ME = ME, RMSE = RMSE, MAE = MAE, MPE = MPE, MAPE = MAPE))
}

# Calcolo delle previsioni
forecast_values <- fitted(tslm_rev)
actual_values <- diff_revenue

# Calcolo degli errori
errors <- calculate_errors(actual_values, forecast_values)

# Visualizzazione dei risultati
print(errors)
```

```{r}
# Libreria necessaria
library(glmnet)

# Combina tutte le variabili in un unico dataframe
data_combined <- data.frame(
  revenue = as.numeric(ts_revenue),
  trend = 1:length(ts_revenue),
  season = as.factor(cycle(ts_revenue)),
  spending = as.numeric(ts_spending),
  net_income = as.numeric(ts_net_income),
  employees = as.numeric(ts_employees)
)

# Preparazione dei dati
X <- model.matrix(ts_revenue ~ ts_spending + ts_net_income, data = data_combined)
y <- ts_revenue



# Ridge Regression
ridge_model <- cv.glmnet(X, y, alpha = 0)  # alpha=0 per Ridge

# Coefficienti del modello
coef(ridge_model, s = "lambda.min")

# Previsioni con Ridge Regression
ridge_predictions <- predict(ridge_model, s = "lambda.min", newx = X)

# Calcolo degli errori per Ridge Regression
ridge_errors <- calculate_errors(y, ridge_predictions)
print(ridge_errors)

```


```{r}
# Caricare i pacchetti necessari
library(ggplot2)
library(forecast)
library(dplyr)

# Creare un data frame con i valori reali e quelli predetti
data <- data.frame(
  Date = time(ts_revenue),
  Revenue = as.numeric(ts_revenue),
  Fitted = fitted(tslm_rev)
)

# Creare il grafico con ggplot2
ggplot(data, aes(x = as.Date(Date))) +  # Conversione della data
  geom_point(aes(y = Revenue)) +  # Valori reali
  geom_line(aes(y = Fitted), color = "red") +  # Valori predetti
  ggtitle("Real Revenue vs Fitted Values with TSLM") +
  xlab("Date") +
  ylab("Revenue")
```

```{r}
library(glmnet)

# Creare la matrice di design per la regressione Lasso
X <- model.matrix(ts_revenue ~ ts_employees + ts_net_income + ts_spending)[, -1]
y <- as.vector(ts_revenue)

# Eseguire la regressione Lasso con cross-validazione
cv_lasso <- cv.glmnet(X, y, alpha = 1)
lasso_model <- glmnet(X, y, alpha = 1)

# Tracciare il grafico dei coefficienti
plot(lasso_model, xvar = "lambda", label = TRUE)

# Calcolare le previsioni della Lasso Regression
lasso_predictions <- predict(lasso_model, s = cv_lasso$lambda.min, newx = X)

# Calcolare i residui
lasso_residuals <- y - lasso_predictions

# Convertire i residui in un oggetto ts
ts_lasso_residuals <- ts(lasso_residuals, frequency = 4)

# Utilizzare checkresiduals per analizzare i residui
checkresiduals(ts_lasso_residuals)

# Creare un data frame con i valori reali e quelli predetti
data <- data.frame(
  Date = as.Date(time(ts_revenue), origin = "1970-01-01"),
  Revenue = as.numeric(ts_revenue),
  Lasso_Fitted = as.numeric(lasso_predictions),
  Residuals = as.numeric(lasso_residuals)
)

# Creare il grafico con ggplot2
ggplot(data, aes(x = Date)) +
  geom_point(aes(y = Revenue), color = "blue") +  # Valori reali
  geom_line(aes(y = Lasso_Fitted), color = "red") +  # Valori predetti dalla Lasso
  ggtitle("Real Revenue vs Fitted Values with Lasso Regression") +
  xlab("Date") +
  ylab("Revenue") +
  theme_minimal()

```

```{r}
# Creare una matrice con le variabili esogene
xreg <- cbind(ts_employees, ts_net_income, ts_spending)

# Utilizzare auto.arima per trovare il miglior modello ARIMA
best_arima_model <- auto.arima(ts_revenue, xreg=xreg)
summary(best_arima_model)

residuals_arima <- residuals(best_arima_model)

# Visualizzare i residui del modello
checkresiduals(best_arima_model)

# Prevedere i prossimi 8 trimestri
forecast_horizon <- 4
forecast_revenue <- forecast(best_arima_model, xreg=xreg, h = forecast_horizon)

# Visualizzare le previsioni
autoplot(forecast_revenue) +
  labs(title = "Revenue Forecast with ARIMA", x = "Date", y = "Revenue (Billion)") +
  autolayer(fitted(best_arima_model), series = "Fitted", PI = FALSE)
```

```{r}
# Creare una matrice con le variabili esogene
xreg <- cbind(ts_employees, ts_net_income, ts_spending)

# Utilizzare auto.arima per trovare il miglior modello ARIMA
best_arima_model <- auto.arima(ts_revenue, xreg = xreg)
summary(best_arima_model)

# Visualizzare i residui del modello
checkresiduals(best_arima_model)

# Prevedere i prossimi 4 trimestri (1 anno)
forecast_horizon <- 8
# Dato che stiamo prevedendo solo 4 trimestri, utilizziamo le stesse variabili esogene
xreg_future <- tail(xreg, forecast_horizon)

# Prevedere i prossimi 4 trimestri
forecast_revenue <- forecast(best_arima_model, xreg = xreg_future, h = forecast_horizon)

# Visualizzare le previsioni
autoplot(forecast_revenue) +
  labs(title = "Revenue Forecast with ARIMA", x = "Date", y = "Revenue (Billion)") +
  autolayer(fitted(best_arima_model), series = "Fitted", PI = FALSE)
```


